project_name: hydectl

before:
    hooks:
        - go mod tidy

builds:
    - env:
        - CGO_ENABLED=0
      goos:
        - linux
      goarch:
        - amd64
        - arm64
        - "386"
      main: ./main.go
      binary: "hydectl-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
      ldflags:
        - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
    - format: tar.gz
      name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
      files:
        - LICENSE
        - README.md

checksum:
    name_template: "checksums.txt"

snapshot:
    name_template: "{{ incpatch .Version }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - "^ci:"
            - "^chore:"

release:
    github:
        owner: HyDE-Project
        name: hydectl
    prerelease: auto
    draft: false
